#!/usr/bin/env bash

source "utils.sh"

# Check if params are enough to go ahead.
branch=$(git symbolic-ref --short -q HEAD)
to=${1:-develop}

# If github cli is installed, use that
if [[ $(gh_exists) ]]; then
    gh pr create --web --head "${branch}" --base "${to}" --title "${branch}"

    exit 0
fi

# $line becomes a string like "git@github.com:organisation/repo.git
# we need to extra the "organisation/repo" part
PR_BASE_URL=$(git remote show origin -n | grep "Fetch" | awk '{print $3}')
PR_BASE_URL=${PR_BASE_URL:15:-4}

open "https://www.github.com/${PR_BASE_URL}/compare/${to}...${branch}"
