#!/usr/bin/env bash

source "utils.sh"

json=$(to_boolean "${longOpts[json]:-0}")

branch=$(current_branch)
hash=$(git log -1 | head -n 1 | cut -c8-)

if [[ "${json}" == 1 ]]; then
    jo branch=${branch} hash=${hash} | jq

    exit 0
fi

parent_branch=$(cat "${GIT_INFO_FILE}" | grep "${branch}" | awk -F ':' '{print $3}')
if [[ "${branch}" == "main" ]]; then
    parent_branch="-"
elif [[ "${branch}" == "master" ]]; then
    parent_branch="-"
    parent_branch="-"
elif [[ "${branch}" == "develop" ]]; then
    parent_branch="master/main"
fi

writeln "Your current branch is <yellow>${branch}</yellow>"
writeln "Your parent branch is <yellow>${parent_branch:-unknown}</yellow>"
writeln "Latest commit hash is <yellow>${hash}</yellow>"
