#!/usr/bin/env bash

source "utils.sh"

# Check if params are enough to go ahead.
repo=$(repo)
branch=$(git symbolic-ref --short -q HEAD)
to=${1:-develop}

# If a branch wasn't specified, determine it by looking in .githistory
if [[ "${1}" == "" && -f "${GIT_INFO_FILE}" ]]; then
    to=$(grep "^${repo}:${branch}" "${GIT_INFO_FILE}" | cut -d':' -f3)
fi

# If github cli is installed, use that
if [[ $(gh_exists) ]]; then
    gh pr create --web --head "${branch}" --base "${to}" --title "${branch}"

    exit 0
fi

open "https://www.github.com/${repo}/compare/${to}...${branch}"
