#!/usr/bin/env bash

source "utils.sh"

git fetch --quiet -p

# Get the current remote branches excluding the current branch, develop, master and main
local_branches=$(git branch | grep -v \* | cut -c3- | grep -Ev "^(develop|master|main)$" | sort)

IFS=$'\n'
for lb in ${local_branches}; do
	# Is this branch in remote?
	exists=$(git branch -r --contains "origin/${lb}" > /dev/null 2>&1 && echo "1" || echo "0")

	if [[ "${exists}" == "0" ]]; then
		writeln "Deleting branch <magenta>${lb}</magenta>"
		git branch --quiet -D "${lb}"
	fi
done
